url: https://www.popcornlabs.com
baseurl: ""

# Site settings
title: Popcorn Labs
description: Personal projects, apps, and thoughts on building software
email: info@popcornlabs.com
tagline: Apps & ideas by Sean Langley

# Theme (custom, no gem)

# Social networks
social:
  - title: github
    url: https://github.com/PopcornLabs

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
