url: https://popcornlabs.github.io
baseurl: ""

# Site settings
title: Popcorn Labs Inc.
email: info@popcornlabs.com
description: We are a full service mobile and web software development shop, specializing in iOS, Android, Flutter, and Angular projects

# Social networks
social:
  - title: x-twitter
    url: https://x.com/popcornlabsinc
  - title: github
    url: https://github.com/PopcornLabs

# Postal address (add as many lines as necessary)
address:
  - line: 1010-109 Front Street East
  - line: Toronto, Ontario, Canada, M5A 4P7

# Build settings
markdown: kramdown
permalink: pretty
