url: https://popcornlabs.github.io
baseurl: ""

# Site settings
title: Popcorn Labs Inc.
description: We are a full service mobile and web software development shop, specializing in iOS, Android, Flutter, and Angular projects
email: info@popcornlabs.com
tagline: Full service mobile and web software development

# Theme
theme: jekyll-theme-midnight

# Social networks
social:
  - title: twitter
    url: http://twitter.com/popcornlabsinc
  - title: github
    url: http://github.com/PopcornLabs

# Postal address
address:
  - line: 1010-109 Front Street East
  - line: Toronto, Ontario, Canada, M5A 4P7

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
